
package(
    default_visibility = [
        "//tensorflow_probability:__subpackages__",
    ],
)


py_library(
    name = "bhge_bayesianGP",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    deps = [
        "//tensorflow_probability/python/models/bhge_bayesianGP/scripts",
    ],
)
